AWSTemplateFormatVersion: '2010-09-09'
Description: RDS PostgreSQL + Secrets Manager for Django App

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 1 ID
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 2 ID
  RdsSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group for RDS

Resources:

  # Secrets Manager: Generate username/password for the DB
  DjangoDBSecretv2:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: django-db-credentials-v2
      Description: "Credentials for Django RDS Postgres (v2)"
      GenerateSecretString:
        SecretStringTemplate: '{"username":"django_user"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludeCharacters: '"@/\\'
      Tags:
        - Key: App
          Value: Django

  # RDS Subnet Group
  DBSubnetGroupv2:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnet group for Django RDS"
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
      DBSubnetGroupName: django-db-subnet-group-v2

  # RDS PostgreSQL Instance
  DjangoDBInstancev2:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: django-postgres-db-v2
      DBName: productivitydb
      AllocatedStorage: 50
      DBInstanceClass: db.t3.micro
      Engine: postgres
      EngineVersion: "15"
      MasterUsername: !Join [ "", [ '{{resolve:secretsmanager:', !Ref DjangoDBSecretv2, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join [ "", [ '{{resolve:secretsmanager:', !Ref DjangoDBSecretv2, ':SecretString:password}}' ] ]
      VPCSecurityGroups:
        - !Ref RdsSecurityGroupId
      DBSubnetGroupName: !Ref DBSubnetGroupv2
      MultiAZ: false
      PubliclyAccessible: false
      DeletionProtection: true
      StorageType: gp3
      BackupRetentionPeriod: 7
      Tags:
        - Key: App
          Value: Django

Outputs:
  DjangoDBEndpointv2:
    Description: RDS Endpoint address (v2)
    Value: !GetAtt DjangoDBInstancev2.Endpoint.Address

  DjangoDBSecretArnv2:
    Description: ARN of Secrets Manager secret (v2)
    Value: !Ref DjangoDBSecretv2
